# Generated by Django 4.1.3 on 2023-11-12 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='subscribed_subreddits', to=settings.AUTH_USER_MODEL),
        ),
    ]
