# Generated by Django 4.1.3 on 2023-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_alter_subreddit_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='subreddit/avatar'),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
