# Generated by Django 4.1.3 on 2023-11-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_customuser_karma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Sports', 'Sports'), ('Art', 'Art'), ('Music', 'Music'), ('Books', 'Books'), ('Movies', 'Movies'), ('Travel', 'Travel'), ('Cooking', 'Cooking'), ('Gaming', 'Gaming'), ('Fitness', 'Fitness'), ('Fashion', 'Fashion'), ('Photography', 'Photography'), ('History', 'History'), ('Nature', 'Nature'), ('Cars', 'Cars'), ('Programming', 'Programming'), ('Crafts', 'Crafts'), ('Dance', 'Dance'), ('Health', 'Health'), ('Politics', 'Politics'), ('Pets', 'Pets'), ('Food', 'Food'), ('Business', 'Business'), ('Anime', 'Anime'), ('Comics', 'Comics'), ('Education', 'Education'), ('Social Issues', 'Social Issues'), ('DIY', 'DIY'), ('Beauty', 'Beauty'), ('Astronomy', 'Astronomy')], null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
