# Generated by Django 4.1.3 on 2023-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_customuser_interests_customuser_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
