# Generated by Django 4.1.3 on 2023-11-19 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saved', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
